service: affective-computing

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  profile: aihackathon
  memorySize: 3008

# TODO: Limit rights in production :-)
iamRoleStatements:
  - Effect: Allow
    Action:
      - s3:*
    Resource: "*"
  - Effect: "Allow"
    Action:
      - "rekognition:*"
    Resource: "*"   

functions:
  main:
    handler: main.handle
    events:
      - http: GET /
  image_upload:
    handler: image_upload.handle
    events:
      - http:
          method: POST
          path: camera/
          cors: true
  image_uploaded:
    handler: image_uploaded.handle
    events:
      - s3:
          bucket: affective-computing
          event: s3:ObjectCreated:*
          rules:
            - prefix: photos/
            - suffix: .jpg
  spotify:
    handler: spotify.handle
    events:
      - http: GET spotify

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
