service: affective-computing

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  profile: aihackathon
  memorySize: 2048
  timeout: 20
  iamRoleStatements: # TODO: Limit rights in production :-)
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "rekognition:*"
      Resource: "*"   

functions:
  next_action:
    handler: next_action.handle
    events:
      - http:
          method: GET
          path: next_action/
          cors: true
  image_upload:
    handler: image_upload.handle
    events:
      - http:
          method: GET
          path: camera/
          cors: true
  image_uploaded:
    handler: image_uploaded.handle
    events:
      - s3:
          bucket: affective-computing
          event: s3:ObjectCreated:*
          rules:
            - prefix: photos/
            - suffix: .png
  spotify:
    handler: spotify.handle
    events:
      - http:
          method: GET
          path: spotify/
          cors: true

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
